### ISSUE TITLE
Duplicate tab in Chrome causes JavaObjects to return undefined

### ISSUE THREAD

**Issue by exevolution** [jneale/Xplore#53] opened 2021-09-10 20:15 UTC
Steps to reproduce:
1. Open an Xplore tab
2. Run method that would return [JavaObject] and its properties.
`gs.getUserID();`
3. Note the results
4. Right click the tab in Chrome and Duplicate
5. Repeat step 2
6. Note the return value is undefined

**Comment by jneale** [comment] 2021-09-13 08:54
Hi, I cannot reproduce this issue. What version of ServiceNow, Xplore, and browser are you using?

**Comment by exevolution** [comment] 2021-09-20 23:54
ServiceNow version: Quebec Patch 4 Hotfix 2b
Xplore version: 4.9
Browser: Chrome 94.0.4606.41 on Windows 10

**Comment by exevolution** [comment] 2021-09-20 23:56
![Screenshot 2021-09-20 165555](https://user-images.githubusercontent.com/12928615/134092057-8a4cf175-ea21-475c-ae8b-f667dd659f41.png)
![Screenshot 2021-09-20 165615](https://user-images.githubusercontent.com/12928615/134092062-85772ab7-1638-48a8-bf47-bfc8ca555735.png)

**Comment by jneale** [comment] 2022-01-14 11:35
Turns out this was a bug with Chrome incorrectly copying the page and turning all the settings on which meant hoisting was enabled on the duplicate page. Hoisting requires a return value which is why it was failing.

It's fixed in 4.10.

**Closed by jneale** 2022-01-14 11:35 UTC
Labels: bug
